# Generated by Django 5.0.7 on 2024-07-13 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mentor',
            name='is_mentor',
            field=models.BooleanField(default=True),
        ),
    ]
