# Generated by Django 5.0.7 on 2024-07-13 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentor', '0002_mentor_is_mentor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mentor',
            name='hourly_rate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='mentor',
            name='specialization',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
