# Generated by Django 5.0.7 on 2024-07-13 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentor', '0003_alter_mentor_hourly_rate_alter_mentor_specialization'),
    ]

    operations = [
        migrations.AddField(
            model_name='mentor',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
    ]
