# Generated by Django 5.0.7 on 2024-08-12 06:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mentor', '0002_initial'),
        ('mentor', '0004_mentor_is_approved'),
    ]

    operations = [
    ]
