# Generated by Django 5.0.7 on 2024-08-12 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentor', '0005_merge_0002_initial_0004_mentor_is_approved'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mentor',
            name='is_approved',
        ),
        migrations.RemoveField(
            model_name='mentor',
            name='is_mentor',
        ),
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('scheduled', 'Scheduled'), ('completed', 'Completed'), ('cancelled_by_user', 'Cancelled by User'), ('cancelled_by_mentor', 'Cancelled by Mentor')], default='scheduled', max_length=25),
        ),
        migrations.AlterField(
            model_name='mentor',
            name='hourly_rate',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='mentor',
            name='specialization',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
