# Generated by Django 5.0.7 on 2024-08-13 13:50

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentor', '0006_remove_mentor_is_approved_remove_mentor_is_mentor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='video_call_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='video_call_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
