# Generated by Django 5.0.7 on 2024-08-13 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentor', '0007_appointment_video_call_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='notification_sent',
            field=models.BooleanField(default=False),
        ),
    ]
