# Generated by Django 5.0.7 on 2024-08-27 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentor', '0009_appointment_agora_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='mentor_user_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
