# Generated by Django 5.0.7 on 2024-08-28 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentor', '0010_appointment_mentor_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='call_duration',
            field=models.DurationField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='call_end_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='call_start_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='mentor_joined',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='appointment',
            name='user_joined',
            field=models.BooleanField(default=False),
        ),
    ]
